language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 0.10

before_install:
  - npm install -g grunt-cli

script:
  - grunt qunit

after_script:
  - node_modules/codeclimate-test-reporter/bin/codeclimate.js < build/lcov.info
